### ISSUE TITLE
Paypal Express IPN

### ISSUE THREAD

**Issue by toddvalentine** [silverstripe/silverstripe-omnipay#156]
I just recently have started getting an error where incorrect TransactionReference is getting set on my Payments. I don't have apache access data back far enough to know if anything has changed on the Paypal end, but the initial IPN response from Paypal is 

"GET /paymentendpoint/bac5ad69c59d319a7172bd4935ab5c/complete?token=EC-XXXXXXXXX&PayerID=XXXXXXXXX HTTP/1.1" 302

milliseconds later I get the following

"POST /paymentendpoint/bac5ad69c59d319a7172bd4935ab5c/notify HTTP/1.1" 200 5690 "-" "PayPal IPN ( https://www.paypal.com/ipn )"

The token in the initial GET request is being set as the TransactionReference on my Payment. So when I attempt to Refund, I get an error.

If I manually update the TransactionReference to the correct one pulled from the IPN request in Paypal and try to Refund I am successful.

Everything was working as recently as 12/4.

**Comment by bummzack** [comment]
What version of omnipay and silverstripe-omnipay are you using?

**Comment by toddvalentine** [comment]
"silverstripe/silverstripe-omnipay": "^2.0"

which requires:

"omnipay/common": "~2.4"

**Comment by bummzack** [comment]
What version of the paypal gateway are you using? eg. omnipay/paypal? Does upgrading to the latest version help?

**Comment by toddvalentine** [comment]
silverstripe/omnipay requires ~2.5, so my composer.lock file is showing v2.6.2 which is the most up to date stable version.

**Comment by bummzack** [comment]
Have you figured out, where things go wrong, eg. which line of code? Is it only when attempting a refund?

**Comment by toddvalentine** [comment]
Things go wrong when the GET request is made and omnipay grabs the token value in the request and sets it as the TransactionReference. Funds are successfully captured, but refunds cannot be made since the Payment has an incorrect reference to the Paypal TransactionID. Very strange that this just started happening. TransactionReference values were getting set correctly as recently as 12/4.

**Comment by bummzack** [comment]
Can you reproduce this issue with the PayPal Sandbox? I just gave it a try and refunds seem to be working fine.

**Comment by toddvalentine** [comment]
Yeah, reproduced on sandbox. Still grabbing the token from the complete status request and using it as TransactionReference. Possibly on a side note, is there a way to disable the module from attempting to write to debug.log? I have tried everything in my config and can't disable, so I get alot of errors. My current config is below:

```
Payment:
  allowed_gateways:
    - 'PayPal_Express'
  file_logging: false

GatewayInfo:
  PayPal_Express:
    parameters:
      username: ‘XXXXXXXX’
      password: '1234567’
      signature: ‘XXXXXXXX’
---
Except:
  environment: 'live'
---
GatewayInfo:
  PayPal_Express:
    parameters:
      testMode: true
---
Only:
  environment: 'live'
---
GatewayInfo:
  PayPal_Express:
    parameters:
      username: ‘XXXXXXXX’
      password: ‘1234567’
      testMode: false
      signature: ‘XXXXXXX’
```

**Comment by bummzack** [comment]
I can't reproduce the issue. I tried normal purchase, as well as authorized/captured amounts and I can refund them without running into the problem. 

Can you show me give me a list of steps to take to reproduce the issue? Are you using silvershop or another shop-system?

**Comment by bummzack** [comment]
Oh boy, I'm stupid. This issue is related to IPN only, right? When you disable IPN, it works?

**Comment by bummzack** [comment]
I don't have any experience with PayPal IPN, but I think the silverstripe-omnipay library isn't properly equipped to deal with that out of the box.

With 2.0 I have implemented asynchronous payment notifications, these can be enabled by using the `use_async_notification` configuration flag. But what this does is, that it sets the payment to "Pending" until the notification comes in. 

However, this approach relies on the `acceptNotification` method in Omnipay, for the payment actions `capture`, `refund` and `void`. So if the gateway doesn't implement `acceptNotification` for these actions, you're out of luck using the async-notification feature.

I think what you're actually experiencing is a race-condition. Since both the `notify` and the `complete` method attempt to finalize the payment, only one can win (a successful call to one of these URLs will set the Payment status to `Complete`, which will lock it for any further changes).

So, your refund will only work, **if** `notify` was called first, since the data from IPN seems to contain the correct transaction-reference. If `complete` gets called first, the transaction reference will be set to the wrong value.

**Comment by toddvalentine** [comment]
Thank you. This makes perfect sense. Looking at the order of calls from Paypal this does seem to be what is occurring. I'll look into the possibility of using async notifications.

I am not using silvershop. I have just have a simple integration where customer fills out a form and is redirected to Paypal for payment.

**Comment by bummzack** [comment]
May I ask, why you need the IPN feature? The regular response should be enough to determine success of the payment…

If you really need the IPN feature, maybe you could use an extension that will make your "complete" purchase call behave as if it was waiting for a notification and only do the actual completion of the purchase when you get the IPN notification.

Something like this could work:

```php
use SilverStripe\Omnipay\Service\ServiceResponse;

class PayPalIpnExtension extends Extension
{
    public function updateServiceResponse(ServiceResponse $serviceResponse)
    {
        if (
            !$serviceResponse->isNotification() // Not a notification, thus not triggered via "notify"
            && $serviceResponse->getPayment()->Gateway === 'PayPal_Express' // we're dealing with PayPal here
        ) {
            // Set the response flag to "Pending", so that the payment waits for the notification to come in
            $serviceResponse->addFlag(ServiceResponse::SERVICE_PENDING);
        }
    }
}
```

And then add it to the purchase service (via config YML)

```yaml
SilverStripe\Omnipay\Service\PurchaseService:
  extensions:
    - PayPalIpnExtension
```

This currently only works with the `master` branch, but I'll release a new version shortly.

**Comment by bummzack** [comment]
I just released 2.1. The code above should work with that version.

**Comment by bummzack** [comment]
Btw, regarding your logging issue: Have you tried setting `file_logging: 0` instead?

**Comment by toddvalentine** [comment]
Thanks alot. I will update and try out your extension. We use IPN because we use the same account integrated with other services that require it.

**Comment by toddvalentine** [comment]
Still getting the token set as transactionReference. I'm not seeing any extend methods in PurchaseService that use the updateServiceResponse method from the Extension you wrote above. Is this correct?

**Comment by bummzack** [comment]
The `updateServiceResponse` hook is in `PaymentService`, but I suggest you extend `PurchaseService`, so that it doesn't get applied to all services…

Maybe you should log all the data you get from PayPal and see, where you actually get the proper transaction-reference? Do you even get it with the IPN response?

**Comment by toddvalentine** [comment]
Yes. The correct transaction reference value is included as txn_id in the IPN response:

    &txn_id=xxxxxxx

**Comment by bummzack** [comment]
I guess that's where the problem arises then… the omnipay paypal gateway doesn't seem to look up the txn_id, see here: https://github.com/thephpleague/omnipay-paypal/blob/v2.6.3/src/Message/ExpressCompletePurchaseResponse.php#L36

Have you tried using the PayPal REST gateway instead of the Express one?

**Comment by toddvalentine** [comment]
I've added a SS_Log call into the extension above and seems like the updateServiceResponse method is not getting called. Trying to understand why...

**Comment by bummzack** [comment]
It should get called, once you applied the extension via YML and run `dev/build`. If not, running a debugger might help.

**Comment by toddvalentine** [comment]
Think I figured it out. I copied the namespace straight from above. SilverStripe was not capitalized correctly! ;)

**Comment by toddvalentine** [comment]
Closing. I can't seem to get to IPN requests working properly with refunds. Thank you very much for all your help here.
